### ISSUE TITLE
[BUG] Stash mixed in with diffs

### ISSUE THREAD

**Issue by joshmedeski** [arl/gitmux#109]
**Describe the bug**
The stash info is being mixed in with the diffs

**To Reproduce**

1. Set the following layout:
```
  layout: [branch, divergence, flags, stats, " "]
```
2. Add a stash and diff some files (modified, added, deleted lines)

**Expected behavior**
I expect the modified, added, deleted to be grouped together, but the stash is mixed in.

**Screenshots**
![SCR-20240119-kqhk](https://github.com/arl/gitmux/assets/2036594/9b606f0f-c6e8-4f5f-9a83-242329a62a1d)

**Environment:**
 - gitmux version: 0.10.4
 - tmux version: tmux 3.3a
 - OS: macOS
 - shell: Fish

**Additional context**
I may be able to fix this myself, but wanted to know if anything has changed recently that you're aware of that would cause this.

**Comment by joshmedeski** [comment]
After some more looking it's happening with new files too:
![SCR-20240119-krze](https://github.com/arl/gitmux/assets/2036594/6763136e-ada7-484e-8797-ec0900893023)

**Comment by arl** [comment]
Uhm strange indeed. Are you able to try with previous gitmux versions, or better to try with a vanilla tmux.conf. I suspect some kind of unexpected interaction with tmux plugins.

**Comment by joshmedeski** [comment]
The changed lines appear to be rendering with the "flags" layout item. I expected that to be apart of "stats" (which is only lines added and lines removed now).

**Comment by arl** [comment]
The `flags` layout elements has always mapped to the following (in that order):
 - staged files count
 - conflicts counts
 - modified files
 - stashed list length
 - untracked files count

 
I've configured the layout as yours: `layout: [branch, divergence, flags, stats, " "]`, on a repository with the following state: 

```sh
$ gitmux -dbg
{
 "NumModified": 1,
 "NumConflicts": 0,
 "NumUntracked": 1,
 "NumStaged": 0,
 "IsDetached": false,
 "IsInitial": false,
 "LocalBranch": "main",
 "RemoteBranch": "origin/main",
 "AheadCount": 0,
 "BehindCount": 0,
 "NumStashed": 2,
 "HEAD": "b821624",
 "State": "default",
 "IsClean": false,
 "Insertions": 4,
 "Deletions": 1
}
```

This is what's being rendered with everything let as default values:

![image](https://github.com/arl/gitmux/assets/476650/e6dca54b-6cde-4fd0-9333-7c7a80ce77df)

- branch
- flags (here we only have `modified`, `stashed` and `untracked` items since nothing has been staged, and there aren't any conflicts
- stats (insertions and deletions)

**Comment by joshmedeski** [comment]
Okay, then it's not a bug! I guess I hadn't noticed and was unsure why modified lines were separated from lines added and removed.

Thanks for the clarification

**Comment by arl** [comment]
> Okay, then it's not a bug! I guess I hadn't noticed and was unsure why modified lines were separated from lines added and removed.

Oh I guess I see where the confusion might have came from, the `stats` element reports added/deleted lines, whereas the 'modified' item of the `flags` element reports the count of modified files.

> Thanks for the clarification
Sure, thanks for reporting in any case!
