### ISSUE TITLE
Feature: breakdown remote into 2 separate layout components

### ISSUE THREAD

**Issue by oberprah** [arl/gitmux#23]
I would like to remove the remote-branch-name from the layout, because it's almost ever the same as the local one (`<branch-name>` and `origin/<branch-name>`).

If I remove `remote` from the layout not only the remote-branch-name isn't displayed anymore, also the information how many commits I am behind or above the origin branch is gone.

Is it possible to add another parameter to the config, e.g. `remote-flags`? Thus, with `remote` I could handle, if the remote-branch-name is displayed or not and with `remote-flags` I could handle, if the number of how many commits I am behind or above the origin branch is displayed or not.

**Comment by arl** [comment]
I reckon you're not the first one to propose this.
I agree this would be nice though I'd like to find a way to do it so that adding it won't break currently existing and valid configurations.
Probably adding some aliases: for example `remote` would be internally split to `remote-branch` + `remote-flags` so that one user with `remote` won't notice the difference whereas an user like you that want more control over that that can chose to only show `remote-flags`.

**Comment by arl** [comment]
@oberprah FYI this is fixed in [latest](https://github.com/arl/gitmux/releases/latest) release
