### ISSUE TITLE
[BUG] After install the bar did not appear

### ISSUE THREAD

**Issue by MorpheusH3x** [arl/gitmux#48]
**Describe the bug**

**To Reproduce**
After downloading gitmux via go, I simply follow [the guide](https://github.com/arl/gitmux/#getting-started).

**Expected behavior**
I should see some thing like [that](https://raw.githubusercontent.com/arl/gitmux/readme-images/demo-small.gif).

**Environment:**
 - gitmux version: `zsh: command not found: gitmux`
 - tmux version: `tmux 3.0a`
 - tmux.conf:
 ```
# Source:
# https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Swap panel to left/right
# https://superuser.com/a/552493
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Reload on the go!
bind -n M-r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Enable mouse mode/ control (clickable windows, panes, resizable panes) [tmux MUST >= 2.1)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename on

# -------------------- #
# -------------------- #
# -------------------- #

# Source:
# https://blog.wescale.fr/2019/03/14/tmux-diviser-pour-mieux-regner/

set -g status-position bottom

# -------------------- #
# -------------------- #
# -------------------- #

set -g history-limit 5000

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'arcticicestudio/nord-tmux'

# Automatic tpm installation (https://github.com/tmux-plugins/tpm/blob/master/docs/automatic_tpm_installation.md)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
 ```
 - OS: Regolith Linux
 - Shell: Zsh

**Additional context**
I think the fact that I use the nord theme for tmux cause a conflict.

**Comment by arl** [comment]
I note 2 things from your report.

1) I see `zsh: command not found: gitmux`. If `zsh` can't access to `gitmux`, `tmux` won't be able either. Can you confirm that `gitmux` binary executable is accessible from your `$PATH`? Otherwise you can  use in 2) the full path to gitmux in case you don't wan't/can't place `gitmux` in your `$PATH`.

2) I can't see in your `.tmux.conf` the line that should be present in order to indicate to `tmux` that it should call `gitmux` .
Try adding the following line at the end of `.tmux.conf`, replacing `/path/to/gitmux` with the actual absolute path to `gitmux`.

set -g status-right '#(/path/to/gitmux "#{pane_current_path}")'

Let me know

**Comment by MorpheusH3x** [comment]
It resolve my problem.
Thank you.
