### ISSUE TITLE
[FEATURE] Is it able to keep running for one panel

### ISSUE THREAD

**Issue by c02y** [arl/gitmux#51]
**Is your feature request related to a problem? Please describe.**

I use gitmux in `pane-border-format`, and if I keep greping gitmux in ps list, the PID is keeping increasing since it runs and exits, it is able to keep the process in a while loop with a delay of course, display the result but not exit the gitmux process, sorry about that I'm a little picky, it is OK if it creates new gitmux process for new tmux pane/window. (I don't know if it is limited by `display-time`)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arl** [comment]
Making Gitmux a daemon seems like a very big change. Is keeping the same PID all along the only benefit wend get out of Gitmux being a daemon, or did you want to achieve something different, prevented by the PID increasing?

**Comment by c02y** [comment]
I just don't want a process to keep running-and-exiting in the background, and don't want its process ID to increase forever.

**Comment by arl** [comment]
@c02y 
`gitmux` is called by `tmux` :
 - when there's a possibility the status bar might be updated  (after you switch panel for example)
 - if nothing happens, at the frequency configured in your tmux.conf with `status-interval`

At the moment, gitmux is updated as soon as possible in the status bar and this is precisely because tmux is calling us.
tmux can only runs process, and not communicate with a daemon.
gitmux is very low in resources and if really the fact that it's called too often is a problem you should increase the status interval.

About the second point, the ever-increasing PID i don't think there's anything we can do to change that.
