### ISSUE TITLE
Add optional replace 'origin' with nerdfont symbol for origin's URL

### ISSUE THREAD

**Issue by sinewalker** [arl/gitmux#69]
**Is your feature request related to a problem? Please describe.**

It would be nice if the remote name was shortened to a symbol representing the host provider, rather than `origin`.

**Describe the solution you'd like**

For remote name (`remote`, or `remote-branch`), when the remote url contains a known public domain for a Git hosting service, replace the remote name string (i.e. "`origin`") with the [Nerd Font UTF8 symbol](https://www.nerdfonts.com/cheat-sheet) for the remote host:

| Host | Match | Icon | Class | Hex | 
| --- | --- | --- | --- | --- |
|GitHub |`github` | `` |`nf-fa-github` |`f09b` |
|GitLab |`gitlab` | `` |`nf-fa-gitlab` |`f296` |
|BitBucket |`bitbucket` | `` |`nf-fa-bitbucket` |`f171` |
| (other) | (other) | `` |`nf-dev-git` |`e702` |

**Describe alternatives you've considered**

- Use the `branch_max_len` and `branch_trim` options. This is not as pretty, can loose information, and is not concise, like the existing flag characters.
- Provide an option to specify some string for the remote
- Use shorter strings or symbols for local remote names. Git defaults to `origin`, and nerd-fonts or other symbols can be difficult to type in `git` commands.

**Additional context**

**Comment by sinewalker** [comment]
Looks like the git status info comes from https://github.com/arl/gitstatus/blob/main/status.go#L37 and this does not have the actual URL. 

So either that needs extending just to support this (seems a lot of effort for a trivial thing), or else the feature suggestion just looks for the remote name "`origin`" and replaces it with an optional string.

**Comment by arl** [comment]
Hi @sinewalker. Thank you for the detailed feature request.

I have to say that I'm merely using a single Git hosting service so I might not be the best person to value that feature.
Though it looks like it could be nice to have, the feature looks very specific and in my humble opinion, does not seem it would add much value to gitmux output. 

There's also something I don't understand: let's say we have 2 branches on a github remote, named `origin/main` and `some-other-branch/main`. If I understand correctly, both of them would be replaced with the same symbol since both of them come from a github remote. How are we going to discern which is which then?

However, if what you want is replacing the `origin` string in gitmux output with something else, you can do that with `sed`:

For example; here I replace `origin` with `⎇`
```
gitmux | sed 's/origin/⎇ /g'
```

Putting it all together in `.tmux.conf`
```
set -g status-right '#(gitmux "#{pane_current_path}" | sed "s/origin/⎇ /g")'
```
Result:
![image](https://user-images.githubusercontent.com/476650/186426551-30485621-34dc-4b58-be57-7a5c19799085.png)

**Comment by sinewalker** [comment]
Thanks very much for this considered reply @arl !  I that a wrapper of some kind which ultimately replaces `origin` with an appropriate symbol is exactly what I need.

**Comment by arl** [comment]
You're welcome. Thank you for your interest in gitmux
❤️

**Comment by sinewalker** [comment]
Here's [a gist with the wrapper I came up with](https://gist.github.com/sinewalker/a8ca548bb8a341b1c947202cc08cb1fe).

**Comment by arl** [comment]
Nice. Thank you for sharing. In case I see there some more interest in that feature and I reconsider I'll be certain to let you know.
Cheers
