### ISSUE TITLE
Edit symbols in gitmux output

### ISSUE THREAD

**Issue by c02y** [arl/gitmux#7]
I'm in an environment(ssh into remote server) that doesn't support all the symbols in gitmux
![gitmux](https://user-images.githubusercontent.com/2135996/68447461-02a59500-021b-11ea-82a7-59bd355aaf96.png)

BTW: I'm using this as my pane-border-format:
~~~
set -g pane-border-format "#[reverse,bold]#(echo '#')#{pane_index}: #{s|$HOME|~|:pane_current_path}#[default] (#(gitmux -q -fmt tmux #{pane_current_path})#[default])"
~~~
NOTE: the `()` would be a problem when in a directory which is not git repo. https://github.com/arl/gitmux/issues/8

Would this be fixed?

**Comment by arl** [comment]
You can override the default symbols by passing your own config to gitmux:

First save the current config
```
$ gitmux -printcfg > .gitmux.cfg
$ cat .gitmux.cfg
tmux:
  symbols:
    branch: '⎇ '
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: ●
    conflict: '✖ '
    modified: '✚ '
    untracked: …
    stashed: '⚑ '
    clean: ✔
  styles:
    state: '#[fg=red,bold]'
    branch: '#[fg=white,bold]'
    remote: '#[fg=cyan]'
    staged: '#[fg=green,bold]'
    conflict: '#[fg=red,bold]'
    modified: '#[fg=red,bold]'
    untracked: '#[fg=magenta,bold]'
    stashed: '#[fg=cyan,bold]'
    clean: '#[fg=green,bold]'
```

Replace the symbols and/or styles you wish to override and the use the following command in `.tmux.conf`
```
$ gitmux -q -fmt tmux -cfg .gitmux.cfg
```

I know this project needs a better readme, it's in my todolist!

About the `()` behaviour, I suggest you to create a simple script that calls gitmux itself, inside the script you can check if gitmux is empty, if that's not the case place the `()` around gitmux output.
Then instead of calling gitmux directly in `.tmux.conf` you'll call your wrapper script.

I don't feel like adding a specific feature for this use case, it's too much specific to your needs, it can easily be handled outside of gitmux.

How does that sound?

**Comment by c02y** [comment]
Using a custom config is a good solution.

About the `()`, I can live without it. I'll try to add  my own solution when I really need it.

Thanks for your reply. I'll just close the issues.
