### ISSUE TITLE
Download Latest Release

### ISSUE THREAD

**Issue by markfaine** [arl/gitmux#74]
Can you add a latest tag or symlink it in some way?  The use case is downloading the newest version from CLI without  knowing the version number of the latest version.  There may already be a way to do this but I can't figure it out if there is.
Thank you

**Comment by arl** [comment]
Hi @markfaine. 
There's no one liner to do that unfortunately, since the version if part of the file name to download.
You'd probably have to use GitHub API or maybe just simply list git tags on the repo and forge the filename you want to download based on the latest tag.

What's your use case? I'm curious

**Comment by arl** [comment]
For reference, it doesn't seen like that is something one can do without some script-fu or additional tools.
More info there https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

**Comment by arl** [comment]
Closing as wontfix since github doesn't support that at the moment.

**Comment by arl** [comment]
fyi see #104
