### ISSUE TITLE
fatal: Unable to create '/path/.git/index.lock': File exists.

### ISSUE THREAD

**Issue by c02y** [arl/gitmux#9]
After using gitmux in tmux, from time to time, a problem occurs to me:
~~~
fatal: Unable to create '/path/.git/index.lock': File exists.
~~~
I think this is because git is kept running in the background inside gitmux with tmux.

and I used an script before using gitmux:
https://github.com/c02y/dotfiles/blob/5cbcbda2d49d0f0458fc404b57c5ab0fbd9def7a/bin/.local/bin/pane-border-format.sh#L50

I use `--no-optional-locks` for `git` command in that script to avoid this problem, could you please fix this issue.

**Comment by arl** [comment]
Thank you for that.
I wasn't aware of this option.
It happened also to me from time to time, though rarely enough to not be on my priority list, but paint enough to be reminded of!
That was the n1 issue that prevented me to publicize gitmux over tmux-gitbar.
Thanks again I'm gonna bake this right into the Go binary so that gitmux can be safely called !!!

**Comment by arl** [comment]
This is fixed in the latest release

**Comment by c02y** [comment]
@arl Yes, I got it when you closed this issue with new commit, thanks.
